CREATE TABLE IF NOT EXISTS api_request_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_ip_hash VARCHAR(64),
    method VARCHAR(10) NOT NULL,
    endpoint VARCHAR(200) NOT NULL,
    status INT NOT NULL,
    latency_ms INT NOT NULL,
    error_code VARCHAR(80)
);

CREATE INDEX IF NOT EXISTS idx_api_request_logs_created_at ON api_request_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_api_request_logs_endpoint ON api_request_logs(endpoint);
CREATE INDEX IF NOT EXISTS idx_api_request_logs_status ON api_request_logs(status);
ALTER TABLE api_request_logs ADD COLUMN IF NOT EXISTS user_id_hash VARCHAR(64);
CREATE INDEX IF NOT EXISTS idx_api_request_logs_user_id_hash ON api_request_logs(user_id_hash);

CREATE TABLE IF NOT EXISTS recommendation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    endpoint VARCHAR(80) NOT NULL,
    emotion VARCHAR(40),
    song_count INT NOT NULL,
    provider VARCHAR(40),
    cached BOOLEAN NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_recommendation_events_created_at ON recommendation_events(created_at);
CREATE INDEX IF NOT EXISTS idx_recommendation_events_endpoint ON recommendation_events(endpoint);
